# Goreleaser configuration for Envgrd
project_name: envgrd

# Build configuration
builds:
  - id: envgrd
    main: ./cmd/envgrd
    binary: envgrd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    flags:
      - -trimpath
    # Skip ARM64 Linux due to CGO cross-compilation toolchain requirements
    # Skip Windows - CGO cross-compilation from Linux requires Windows toolchain
    skip:
      - goos: linux
        goarch: arm64
      - goos: windows

# Archive configuration
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Release configuration
release:
  mode: replace
  header: |
    ## Envgrd {{ .Tag }}
    
    Automated release via [GoReleaser](https://goreleaser.com)
  footer: |
    ---
    
    Built with ❤️ by [GoReleaser](https://github.com/goreleaser/goreleaser)
  
  # Mark pre-releases (tags containing '-')
  prerelease: auto

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

