# Goreleaser configuration for macOS builds
project_name: envgrd

# Build configuration
builds:
  # macOS builds (both architectures)
  - id: envgrd-darwin
    main: ./cmd/envgrd
    binary: envgrd
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    flags:
      - -trimpath

# Archive configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

# Checksums - skip for macOS since Linux job already creates checksums.txt
# checksum:
#   name_template: 'checksums.txt'
#   algorithm: sha256

# Release configuration
release:
  mode: append
  header: |
    ## Envgrd {{ .Tag }}
    
    Automated release via [GoReleaser](https://goreleaser.com)
  footer: |
    ---
    
    Built with ❤️ by [GoReleaser](https://github.com/goreleaser/goreleaser)
  
  # Mark pre-releases (tags containing '-')
  prerelease: auto

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

