# Goreleaser configuration for Linux and Windows builds
project_name: envgrd

# Build configuration
builds:
  # Linux builds (amd64 only - ARM64 requires native build)
  - id: envgrd-linux
    main: ./cmd/envgrd
    binary: envgrd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    flags:
      - -trimpath
  # Windows builds skipped - CGO cross-compilation from Linux requires Windows toolchain
  # Windows users should build from source: make build

# Archive configuration
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Release configuration
release:
  mode: replace
  header: |
    ## Envgrd {{ .Tag }}
    
    Automated release via [GoReleaser](https://goreleaser.com)
  footer: |
    ---
    
    Built with ❤️ by [GoReleaser](https://github.com/goreleaser/goreleaser)
  
  # Mark pre-releases (tags containing '-')
  prerelease: auto

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

